/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ClientFeedbackList: typeof import('./src/components/employee/ClientFeedbackList.vue')['default']
    ClientLayout: typeof import('./src/components/layout/ClientLayout.vue')['default']
    ClientReviewLayout: typeof import('./src/components/layout/ClientReviewLayout.vue')['default']
    CredibilitySection: typeof import('./src/components/home/CredibilitySection.vue')['default']
    CTASection: typeof import('./src/components/home/CTASection.vue')['default']
    EmployeeLayout: typeof import('./src/components/layout/EmployeeLayout.vue')['default']
    FileUpload: typeof import('./src/components/employee/FileUpload.vue')['default']
    FooterSection: typeof import('./src/components/layout/FooterSection.vue')['default']
    HeaderNav: typeof import('./src/components/layout/HeaderNav.vue')['default']
    HeroSection: typeof import('./src/components/home/HeroSection.vue')['default']
    LoginForm: typeof import('./src/components/auth/LoginForm.vue')['default']
    MinimalLayout: typeof import('./src/components/layout/MinimalLayout.vue')['default']
    PasswordDialog: typeof import('./src/components/employee/PasswordDialog.vue')['default']
    ProfileDialog: typeof import('./src/components/employee/ProfileDialog.vue')['default']
    ProjectForm: typeof import('./src/components/employee/ProjectForm.vue')['default']
    QRCodeDisplay: typeof import('./src/components/employee/QRCodeDisplay.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServicesOverview: typeof import('./src/components/home/ServicesOverview.vue')['default']
    TestimonialsSection: typeof import('./src/components/home/TestimonialsSection.vue')['default']
  }
}
